PORT=/dev/ttyUSB0
BOARD = atmega328

# GLFAG = 
# OFLAG = -Os
AVRDUDECONFIG = -D -C /etc/avrdude.conf
SKETCHBOOK    = .
ARDUINO       = $(SKETCHBOOK)
HARDWARE_DIR  = $(SKETCHBOOK)/arduino
#BUILDROOT     = ./build

include $(SKETCHBOOK)/arduino/Arduino.mk
